name: CI

# Run action on every push and pull request
on: [push, pull_request]

jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      # Install NodeJS
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'
      
      # Run the server tests
      - name: Run Server Tests
        working-directory: './server'
        run: |
          npm i
          npm run test:docker:github
